export const images = {
  send: require('./images/send.png'),
  google: require('./images/googleicon.png'),
  word: require('./images/word.png'),
  // files
  pdf: require('./images/pdf.png'),
  doc: require('./images/doc.png'),
  // jpg : require('./images/jpg.png'),
  text: require('./images/txt.png'),
  map: require('./images/map.png'),
  jfif: require('./images/jfif.png'),
  forgotPass: require('./images/verify.png'),
  noInternet: require('./images/noInternet.png'),
  nothingFound: require('./images/nothingFound.png'),
  forgotPassEmail: require('./images/forgotPass.png'),
  meetBefore: require('./images/metBefore.png'),
  // excel: require('./images/excel.png'),
  // powerpoint: require('./images/powerpoint.png'),
  organizationLogo: require('./images/organizationLogo.png'),
  lsr: require('./images/icons/lsr.png'),
  nearMiss: require('./images/icons/nearmiss.png'),

  menuIcons: {
    edit: require('./images/more/edit.png'),
    observation: require('./images/more/observation.png'),
    incident: require('./images/more/incident.png'),
    audit: require('./images/more/audit.png'),
    risk: require('./images/more/risk.png'),
    lms: require('./images/more/lms.png'),
    data: require('./images/more/data.png'),
    settings: require('./images/more/settings.png'),
    signout: require('./images/more/signout.png'),
  },
  homeIcon: {
    auditAndReporting: require('./images/icons/auditandreporting.png'),
    dataanalytics: require('./images/icons/dataanalytics.png'),
    incidentreporting: require('./images/icons/incidentreporting.png'),
    lms: require('./images/icons/lms.png'),
    observationfeedback: require('./images/icons/observationfeedback.png'),
    riskmanagement: require('./images/icons/riskmanagement.png'),
  },
  bottomTab: {
    home: require('./images/tab/home.png'),
    home_selected: require('./images/tab/home_selected.png'),
    menu: require('./images/tab/menu.png'),
    menu_selected: require('./images/tab/menu_selected.png'),
    message: require('./images/tab/message.png'),
    message_selected: require('./images/tab/message_selected.png'),
    sors: require('./images/tab/sors.png'),
    sors_selected: require('./images/tab/sors_selected.png'),
    folder: require('./images/tab/folder.png'),
    note: require('./images/tab/note.png'),
  },
};
