import Chart from './chart/Chart';
import Suggestions from './suggestions/Suggestions';
import Card from './card/Card';
import Search from './searchBar/SearchBar';
import User from './Messaging/User/User';
import Tags from "./tags/Tags";
import Header from './header/Header';
import SuggestionsAvatar from "./suggestionsAvatar/SuggestionsAvatar";
import RepeatedSor from './RepeatedSorModal/RepeatedSor';
import  ListCard from "./listCard/ListCard";
import  Comments from "./ViewSor/Popup/Comments/Comments";
export {Suggestions, Chart, Card, Search, User, Header,ListCard, RepeatedSor,Tags, SuggestionsAvatar,Comments};
